<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $categories = DB::table('categories')->pluck('id', 'name');

        $products = [
            [
                'name' => 'Cải ngọt',
                'description' => 'Cải ngọt tươi ngon',
                'price' => 20000,
                'quantity' => 100,
                'category_name' => 'Rau Củ',
                'images' => '["01JRA6Y22TTBAZXHRRQTYP1DDN.webp","01JRA6ZF3384ZN1T9BRTM0T8S1.webp"]',
            ],
            [
                'name' => 'Cà rốt',
                'description' => 'Cà rốt tươi sạch',
                'price' => 15000,
                'quantity' => 50,
                'category_name' => 'Rau Củ',
                'images' => '["01JRA5Y8ME41FWVYSFYRH90JB1.jpg"]',
            ],
            [
                'name' => 'Rau muống',
                'description' => 'Rau muống tươi ngon',
                'price' => 10000,
                'quantity' => 30,
                'category_name' => 'Rau Củ',
                'images' => '["01JRA6V78FFDXDK4HE6XM78XP6.jpg"]',
            ],
            [
                'name' => 'Bông cải xanh',
                'description' => 'Bông cải xanh tươi ngon',
                'price' => 25000,
                'quantity' => 80,
                'category_name' => 'Rau Củ',
                'images' => '["caixanh.jpg" , "caixanh2.jpg"]',
            ],
            [
                'name' => 'Cà chua',
                'description' => 'Cà chua chín đỏ',
                'price' => 18000,
                'quantity' => 70,
                'category_name' => 'Rau Củ',
                'images' => '["cachua1.webp" , "cachua2.webp"]',
            ],
            [
                'name' => 'Khoai tây',
                'description' => 'Khoai tây tươi sạch',
                'price' => 20000,
                'quantity' => 90,
                'category_name' => 'Rau Củ',
                'images' => '["khoaitay1.jpg" , "khoaitay2.jpg"]',
            ],
            [
                'name' => 'Hành tây',
                'description' => 'Hành tây chất lượng cao',
                'price' => 22000,
                'quantity' => 60,
                'category_name' => 'Rau Củ',
                'images' => '["hanhtay.jpg" ,"hanhtay2.jpg"]',
            ],
            [
                'name' => 'Cải thìa',
                'description' => 'Cải thìa tươi ngon',
                'price' => 15000,
                'quantity' => 85,
                'category_name' => 'Rau Củ',
                'images' => '["caithia.png", "caithia2.jpg"]',
            ],
            [
                'name' => 'Su su',
                'description' => 'Su su tươi sạch',
                'price' => 12000,
                'quantity' => 75,
                'category_name' => 'Rau Củ',
                'images' => '["susu1.webp" , "susu2.jpg"]',
            ],
            [
                'name' => 'Bí đỏ',
                'description' => 'Bí đỏ chất lượng',
                'price' => 18000,
                'quantity' => 65,
                'category_name' => 'Rau Củ',
                'images' => '["bido.jpg", "bido2.webp"]',
            ],

            // Danh mục Thịt (cần 10 sản phẩm)
            [
                'name' => 'Thịt bò',
                'description' => 'Thịt bò tươi ngon',
                'price' => 200000,
                'quantity' => 20,
                'category_name' => 'Thịt',
                'images' => '["01JRA616365EZ39M0S5Q6VF7WC.jpg"]',
            ],
            [
                'name' => 'Thịt heo',
                'description' => 'Thịt heo tươi ngon',
                'price' => 100000,
                'quantity' => 40,
                'category_name' => 'Thịt',
                'images' => '["01JRA67ZR0E0RJ84S7SE7237WB.jpg"]',
            ],
            [
                'name' => 'Thịt gà',
                'description' => 'Thịt gà tươi sạch',
                'price' => 80000,
                'quantity' => 50,
                'category_name' => 'Thịt',
                'images' => '["thitga1.webp","thitga2.webp"]',
            ],
            [
                'name' => 'Thịt cừu',
                'description' => 'Thịt cừu chất lượng',
                'price' => 250000,
                'quantity' => 15,
                'category_name' => 'Thịt',
                'images' => '["thitcuu1.jfif","thitcuu2.jpg"]',
            ],
            [
                'name' => 'Thịt vịt',
                'description' => 'Thịt vịt tươi ngon',
                'price' => 90000,
                'quantity' => 35,
                'category_name' => 'Thịt',
                'images' => '["thitvit.webp","thitvit2.webp"]',
            ],
            [
                'name' => 'Thịt dê',
                'description' => 'Thịt dê sạch',
                'price' => 180000,
                'quantity' => 25,
                'category_name' => 'Thịt',
                'images' => '["thitde1.jpg","thitde2.jpg"]',
            ],
            [
                'name' => 'Thịt ngỗng',
                'description' => 'Thịt ngỗng tươi ngon',
                'price' => 120000,
                'quantity' => 30,
                'category_name' => 'Thịt',
                'images' => '["thitngong.jpg", "thitngong2.jpg"]',
            ],
            [
                'name' => 'Thịt thỏ',
                'description' => 'Thịt thỏ sạch',
                'price' => 150000,
                'quantity' => 20,
                'category_name' => 'Thịt',
                'images' => '["thittho1.webp", "thittho2.jpg"]',
            ],
            [
                'name' => 'Thịt lợn rừng',
                'description' => 'Thịt lợn rừng chất lượng',
                'price' => 200000,
                'quantity' => 10,
                'category_name' => 'Thịt',
                'images' => '["lonrung.jpg" , "lonrung2.jpg"]',
            ],
            [
                'name' => 'Thịt bồ câu',
                'description' => 'Thịt bồ câu tươi ngon',
                'price' => 130000,
                'quantity' => 40,
                'category_name' => 'Thịt',
                'images' => '["bocau1.jpg", "bocau2.jpg"]',
            ],

            // Danh mục Cá (cần 10 sản phẩm)
            [
                'name' => 'Cá hồi',
                'description' => 'Cá hồi tươi ngon',
                'price' => 300000,
                'quantity' => 10,
                'category_name' => 'Cá',
                'images' => '["01JRA65QEN79BVS1FZ984538A5.jpg"]',
            ],
            [
                'name' => 'Cá basa',
                'description' => 'Cá basa tươi ngon',
                'price' => 60000,
                'quantity' => 30,
                'category_name' => 'Cá',
                'images' => '["01JRA6FDZEKGEEDRZJ1KWDP7BJ.jpg"]',
            ],
            [
                'name' => 'Cá thu',
                'description' => 'Cá thu tươi sạch',
                'price' => 80000,
                'quantity' => 25,
                'category_name' => 'Cá',
                'images' => '["cathu1.jpg","cathu2.jpg"]',
            ],
            [
                'name' => 'Cá trê',
                'description' => 'Cá trê chất lượng',
                'price' => 50000,
                'quantity' => 40,
                'category_name' => 'Cá',
                'images' => '["cache1.jpg", "cache2.png"]',
            ],
            [
                'name' => 'Cá lóc',
                'description' => 'Cá lóc tươi ngon',
                'price' => 70000,
                'quantity' => 35,
                'category_name' => 'Cá',
                'images' => '["caloc1.jpg", "caloc2.jpg"]',
            ],
            [
                'name' => 'Cá ngừ',
                'description' => 'Cá ngừ chất lượng cao',
                'price' => 150000,
                'quantity' => 20,
                'category_name' => 'Cá',
                'images' => '["cangu1.webp", "cangu2.jpg"]',
            ],
            [
                'name' => 'Cá rô phi',
                'description' => 'Cá rô phi tươi sạch',
                'price' => 45000,
                'quantity' => 50,
                'category_name' => 'Cá',
                'images' => '["carophi.jfif", "carophi2.png"]',
            ],
            [
                'name' => 'Cá chép',
                'description' => 'Cá chép tươi ngon',
                'price' => 55000,
                'quantity' => 30,
                'category_name' => 'Cá',
                'images' => '["cachep.jpg", "cachep2.jfif"]',
            ],
            [
                'name' => 'Cá nục',
                'description' => 'Cá nục chất lượng',
                'price' => 65000,
                'quantity' => 45,
                'category_name' => 'Cá',
                'images' => '["canuc.jpg","canuc2.jpg"]',
            ],
            [
                'name' => 'Cá kiếm',
                'description' => 'Cá kiếm tươi ngon',
                'price' => 200000,
                'quantity' => 15,
                'category_name' => 'Cá',
                'images' => '["cakiem.jpg", "cakiem2.png"]',
            ],

            // Danh mục Trái cây (cần 10 sản phẩm)
            [
                'name' => 'Dưa hấu',
                'description' => 'Dưa hấu tươi ngon',
                'price' => 20000,
                'quantity' => 100,
                'category_name' => 'Trái cây',
                'images' => '["01JRA6GJNRHQE72Q560HGVHGPC.jpg"]',
            ],
            [
                'name' => 'Xoài',
                'description' => 'Xoài tươi ngon',
                'price' => 30000,
                'quantity' => 60,
                'category_name' => 'Trái cây',
                'images' => '["01JRA6K80J207Q90BJYA5S3TYW.jpg"]',
            ],
            [
                'name' => 'Táo',
                'description' => 'Táo tươi ngon',
                'price' => 50000,
                'quantity' => 40,
                'category_name' => 'Trái cây',
                'images' => '["01JRA6RWD1X6Q7Z7B1YVE0QFHN.jpg"]',
            ],
            [
                'name' => 'Chuối',
                'description' => 'Chuối chín vàng',
                'price' => 25000,
                'quantity' => 90,
                'category_name' => 'Trái cây',
                'images' => '["chuoi1.webp", "chuoi2.jpeg"]',
            ],
            [
                'name' => 'Cam',
                'description' => 'Cam tươi ngon',
                'price' => 35000,
                'quantity' => 70,
                'category_name' => 'Trái cây',
                'images' => '["cam1.webp", "cam2.webp"]',
            ],
            [
                'name' => 'Lê',
                'description' => 'Lê chất lượng cao',
                'price' => 45000,
                'quantity' => 50,
                'category_name' => 'Trái cây',
                'images' => '["le1.jpg", "le2.webp"]',
            ],
            [
                'name' => 'Nho',
                'description' => 'Nho tươi ngon',
                'price' => 60000,
                'quantity' => 60,
                'category_name' => 'Trái cây',
                'images' => '["nho1.jfif" , "nho2.jfif"]',
            ],
            [
                'name' => 'Dứa',
                'description' => 'Dứa chín vàng',
                'price' => 30000,
                'quantity' => 80,
                'category_name' => 'Trái cây',
                'images' => '["dua1.webp", "dua2.jpg"]',
            ],
            [
                'name' => 'Măng cụt',
                'description' => 'Măng cụt tươi ngon',
                'price' => 70000,
                'quantity' => 40,
                'category_name' => 'Trái cây',
                'images' => '["mancuc1.jpg", "mancuc2.jpg"]',
            ],
            [
                'name' => 'Vải',
                'description' => 'Vải chín đỏ',
                'price' => 40000,
                'quantity' => 70,
                'category_name' => 'Trái cây',
                'images' => '["vai1.jpg", "vai2.webp"]',
            ],
        ];

        foreach ($products as $product) {
            $categoryId = $categories[$product['category_name']] ?? null;
            if ($categoryId) {
                DB::table('products')->insert([
                    'name' => $product['name'],
                    'description' => $product['description'],
                    'price' => $product['price'],
                    'quantity' => $product['quantity'],
                    'category_id' => $categoryId,
                    'images' => $product['images'],
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }
    }
}
